source "https://rubygems.org"
gem "jekyll-include-cache"

# use local theme gem for testing
gem "minimal-mistakes-jekyll", :git => "https://github.com/mmistakes/minimal-mistakes.git", :tag => "4.24.0"
group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.0'
end

gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "webrick"