gem 'jekyll-include-cache'
plugins:
  - jekyll-include-cache

#theme: jekyll-theme-minimal
title: Paolo E. Valcarcel Pineda
logo: ./Views/Programando.png
description: Economics MSc student at Universidad de los Andes
email: "p.valcarcel@uniandes.edu.co"
linkedin: "https://www.linkedin.com/in/paolo-emmanuel-valcarcel-pineda/"
twitter: "@paolo_valcarcel"
repository: "https://github.com/PaoloValcarcel"
gitlab: "https://gitlab.com/PaoloValcarcel" 
