theme: jekyll-theme-minimal
title: Paolo E. Valcarcel Pineda
email: p.valcarcel@uniandes.edu.co
description: Economics MSc student at Universidad de los Andes
baseurl: ""
url: "https://github.com/PaoloValcarcel"
<!-- Location -->
<a href="https://www.google.com/maps/place/Bogotá/@4.6486259,-74.2478944,11z/data=!3m1!4b1!4m5!3m4!1s0x8e3f9bfd2da6cb29:0x239d635520a33914!8m2!3d4.7109886!4d-74.072092" style="color:black;"> <img alt="Qries" src="./Views/location.png" width=30" height="30">  Bogotá, Colombia.</a>
# Build settings
markdown: kramdown


gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - packrat
