# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Paolo E. Valcarcel Pineda
tagline:          'A Jekyll theme'
description:      'Economics MSc student at Universidad de los Andes'
#url:              http://hyde.getpoole.com
#baseurl:          /

#author:
  #name:           'Paolo E. Valcarcel Pineda'

twitter:         https://twitter.com/paolo_valcarcel

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/PaoloValcarcel
