theme: jekyll-theme-minimal
title: Paolo Valcarcel Pineda
description: Soy estudiante de la Maestría de Economía Aplicada (MEcA) en la Universidad de los Andes (Colombia). Anteriormente me gradué de Economista de la Universidad Nacional del Callao (Perú). 
description: Mis intereses son regulación económica, economía ambiental, economía productiva, Big Data y econometría aplicada.
