theme: jekyll-theme-minimal
title: Paolo E. Valcarcel Pineda
logo: ./Views/Programando.png
email: p.valcarcel@uniandes.edu.co
description: Economics MSc student at Universidad de los Andes
baseurl: ""
repository: "https://github.com/PaoloValcarcel"
url: "https://paolovalcarcel.github.io/"
twitter: @paolo_valcarcel
